### ISSUE TITLE
Mark text to be compared a a block, instead of individual components

### ISSUE THREAD

**Issue by martys** [Rohland/htmldiff.net#12]
![image](https://cloud.githubusercontent.com/assets/210054/8353052/4e0369e8-1b32-11e5-843e-4e635577b5cb.png)

How Can I get the Date compared as a single block ?

**Comment by iamdjones** [comment]
parse complete dates out of the input before passing it on?

**Comment by martys** [comment]
Not really... it's a Html report, that's generated by some service. And I have 2 of these on my hands, and need to compare them..

Ideally - I would want some tab like <span> or <b> or any other to be used to group stuff together

**Comment by Rohland** [comment]
@martys @iamdjones I've implemented block support as I think it's a valid scenario to treat sequences of text as a single block.

Updated usage:

```C#
HtmlDiff.HtmlDiff diffHelper = new HtmlDiff.HtmlDiff(oldText, newText);

// Lets add a block expression to group blocks we care about (such as dates)
diffHelper.AddBlockExpression(new Regex(@"[\d]{1,2}[\s]*(Jan|Feb)[\s]*[\d]{4}", RegexOptions.IgnoreCase));

var result = diffHelper.Build();
```
Note that if one or more expressions overlap, an argument exception will be thrown with the detail of the overlapping expression.

Hope this helps!
