### ISSUE TITLE
NuGet package 1.2 appears to contain old code

### ISSUE THREAD

**Issue by gellmaster** [Rohland/htmldiff.net#17]
Thanks for putting this project out there, it’s really helped our team.

We too wanted to better display date differences (ours are US centric with optional time) and were looking forward to using the newly added AddBlockExpression. #12 

```C# 
diffHelper.AddBlockExpression(new Regex(@"(0?[1-9]|1[012])\/(0?[1-9]|[12][0-9]|3[01])\/\d{4} ([012]{0,1}[0-9]:[0-6][0-9])? [AM|PM]?", RegexOptions.IgnoreCase));
```

After adding NuGet package 1.2, AddBlockExpression appears to be missing. I noticed the release notes and assembly versions are marked as 1.1 still. I pulled down the code and built the package and it worked. Is it possible that you didn’t rebuild your project in release mode before publishing to NuGet?

I’m not sure of the best way to build a NuGet package but maybe consider a project post-build event and package from a [project file](https://docs.nuget.org/create/creating-and-publishing-a-package#from-a-project). 

Maybe something like:
`NuGet.exe pack "$(ProjectPath)" -p Configuration=$(Configuration) -o "$(OutDir)" -symbols`

You could then utilize one of the assembly version attributes to ensure version info is passed automatically and any other replacement token. I believe you could also simplify the nuspec a little by removing pdb file include since the -symbols switch will essentially do that.

Thanks again!

**Comment by Rohland** [comment]
@gellmaster sorry about the long delay in attending to this! It should be sorted now. Version 1.3 has been published. Hopefully this time round it actually contains the latest code ;)
