### ISSUE TITLE
Taking long time to generate out put...

### ISSUE THREAD

**Issue by roboasimo** [Rohland/htmldiff.net#4]
For 9 page file the time is about 13 minutes.
Since comparison is taking place char by char...
Is there any way to compare word by word..??

please reply to  roboasimo@gmail.com

**Comment by Rohland** [comment]
@roboasimo - have a look at the latest commit (70d90f998fff914e09b7195943f2f22e26d523e5) after some refactoring by @yuriy-nelipovich. This might help you. Haven't released this version yet as there are a few other bugs I'd like to attend to. Let me know if it helps.

**Comment by Rohland** [comment]
@roboasimo there are a few enhancements that been made recently which may help you. Have a look a new configuration options on the HtmlDiff class (such as MatchGranularityMaximum).

Closing this issue for now.

**Comment by roboasimo** [comment]
@Rohland, 
Thank you for your effort, We used Xyvision to  compare the inputs, Your approach also works very well..
Thank you,   

@dhruwal ,
   Your suggestion is one of the point when there is slowness on the page, However in my project, we don't use View State as enabled.
Thank you dhruwal
